export { default as Cards} from './Cards/Cards'
export { default as Card} from './Card/Card'
export { default as BasicTable} from './Table/Table'
export { default as Updates} from './Updates/Updates'
export { default as CustomerReview} from './CustomerReview/CustomerReview'